version: '3.8'
services: 
    master:
        build:
            context: ./master/
        container_name: master
        # env_file: ./.env
        command: ["node" ,"app.js"]
        volumes: 
            - ./files/master:/home/node/app/uploads
            # - .:/app/
            # - /app/node_modules
        ports:
            - 8082:8082
        depends_on: 
            - mongodb
        environment: 
            MONGO_HOST: mongodb
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_PORT: 27017
            MONGO_DB: distributedfilesystem
            TOKEN_KEY: jwtsecret
        networks:
            - db-networks
            - backend
    node1:
        build:
            context: ./node1/
        container_name: node1
        # env_file: ./.env
        command: ["node" ,"app.js"]
        volumes: 
            # - .:/app/
            # - /app/node_modules
            - ./files/node1:/home/node/app/uploads
        ports:
            - 8083:8083
        networks:
            - backend
    node2:
        build:
            context: ./node2/
        container_name: node2
        # env_file: ./.env
        command: ["node" ,"app.js"]
        volumes: 
            # - .:/app/
            # - /app/node_modules
            - ./files/node2:/home/node/app/uploads
        ports:
            - 8084:8084
        networks:
            - backend

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        networks:
            - db-networks  
        volumes:
            - mongodb:/var/lib/mongodb

volumes:
    mongodb:

networks:
  db-networks:
  backend:
  
